// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_efNXy1Ku5U1LbTHk9by7F_kLDFQnp8',
    appId: '1:268663195179:web:dd33c2b8971e02f41f0c6e',
    messagingSenderId: '268663195179',
    projectId: 'flutter-not-app-aac0a',
    authDomain: 'flutter-not-app-aac0a.firebaseapp.com',
    storageBucket: 'flutter-not-app-aac0a.appspot.com',
    measurementId: 'G-FT7ZRX3ZBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB973qUnrUZVP_rnkq8PfxzV7_O9JDy98U',
    appId: '1:268663195179:android:9e5c509b9d6d6cee1f0c6e',
    messagingSenderId: '268663195179',
    projectId: 'flutter-not-app-aac0a',
    storageBucket: 'flutter-not-app-aac0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1P2H2EJMn4j8zV-Ipyyn_l_KTi5_HvRs',
    appId: '1:268663195179:ios:a26ae577bd7cbc341f0c6e',
    messagingSenderId: '268663195179',
    projectId: 'flutter-not-app-aac0a',
    storageBucket: 'flutter-not-app-aac0a.appspot.com',
    iosClientId: '268663195179-jv1bllop71bc8j1ogobim7b1s73g3nks.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1P2H2EJMn4j8zV-Ipyyn_l_KTi5_HvRs',
    appId: '1:268663195179:ios:a26ae577bd7cbc341f0c6e',
    messagingSenderId: '268663195179',
    projectId: 'flutter-not-app-aac0a',
    storageBucket: 'flutter-not-app-aac0a.appspot.com',
    iosClientId: '268663195179-jv1bllop71bc8j1ogobim7b1s73g3nks.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );
}
